id: A9C92AF3C
title: f613E
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:44:06.707238
  last_modified_at: 2022-05-27 15:44:06.707240
