id: A9C92AF3C
title: f2959
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:44:06.664585
  last_modified_at: 2022-05-27 15:44:06.664588
